import { createElement } from 'lwc';
import ALU_HomePage_REVA from 'c/aLU_HomePage_REVA';

describe('c-a-l-u-home-page-reva', () => {
    afterEach(() => {
        // The jsdom instance is shared across test cases in a single file so reset the DOM
        while (document.body.firstChild) {
            document.body.removeChild(document.body.firstChild);
        }
    });

    it('TODO: test case generated by CLI command, please fill in test logic', () => {
        // Arrange
        const element = createElement('c-a-l-u-home-page-reva', {
            is: ALU_HomePage_REVA
        });

        // Act
        document.body.appendChild(element);

        // Assert
        // const div = element.shadowRoot.querySelector('div');
        expect(1).toBe(1);
    });
});